// प्लान नोड की सरल व्याख्या। नोड के नाम (Seq Scan आदि) EXPLAIN जैसे ही रहते हैं।
export const planNodes: Record<string, string> = {
  "Seq Scan": "टेबल का हर पेज क्रम से पढ़ता है और हर पंक्ति को फ़िल्टर से जाँचता है। तब सबसे अच्छा जब बहुत-सी पंक्तियाँ मेल खाएँ, या कोई काम का इंडेक्स न हो।",
  "Index Scan": "मेल खाती keys ढूँढने के लिए इंडेक्स पर चलता है, फिर हर पंक्ति टेबल से लाता है। कुछ पंक्तियों के लिए बढ़िया, और उन्हें इंडेक्स के क्रम में लौटाता है।",
  "Index Only Scan": "टेबल पर गए बिना सिर्फ़ इंडेक्स से जवाब देता है, जब हर ज़रूरी कॉलम इंडेक्स में हो और पेज all-visible (सबको दिखने वाले) चिह्नित हों।",
  "Bitmap Index Scan": "इंडेक्स स्कैन करके उन टेबल पेजों का bitmap (चिह्नों का नक्शा) बनाता है जिनमें मेल हैं। Bitmap Heap Scan को डेटा देता है।",
  "Bitmap Heap Scan": "bitmap में चिह्नित पेज भौतिक क्रम में पढ़ता है, शर्त दोबारा जाँचते हुए। index और sequential scan के बीच का रास्ता।",
  "Nested Loop": "बाहरी (पहले) इनपुट की हर पंक्ति के लिए अंदरूनी इनपुट में मेल खाती पंक्तियाँ ढूँढता है। तब तेज़ जब बाहरी हिस्सा छोटा हो और अंदरूनी पर इंडेक्स हो।",
  "Hash Join": "छोटे इनपुट से hash table बनाता है, फिर दूसरे इनपुट को उसमें खोजता है। बड़े, बिना क्रम वाले बराबरी के join के लिए अच्छा।",
  "Merge Join": "join key पर पहले से क्रमबद्ध दो इनपुट को साथ-साथ चलते हुए जोड़ता है।",
  "Hash": "ऊपर वाले Hash Join के लिए मेमोरी में hash table बनाता है।",
  "Sort": "अपने इनपुट को sort करता है, मेमोरी में या डिस्क पर फैलाकर। अक्सर ऐसे इंडेक्स से बचा जा सकता है जो पंक्तियाँ पहले से क्रम में देता हो।",
  "Incremental Sort": "जब इनपुट keys के शुरुआती हिस्से से पहले से क्रमबद्ध हो, तब sort पूरा करता है।",
  "Aggregate": "अपने इनपुट पर count() या sum() जैसे aggregate निकालता है।",
  "HashAggregate": "hash table से पंक्तियों के समूह बनाता है, फिर हर समूह के aggregate निकालता है।",
  "GroupAggregate": "group key से पहले से क्रमबद्ध इनपुट पर, एक-एक समूह करके aggregate निकालता है।",
  "Limit": "पहली N पंक्तियों के बाद रुक जाता है, ताकि नीचे के नोड भी अक्सर जल्दी रुक सकें।",
  "WindowAgg": "क्रमबद्ध partitions पर rank() या running sum जैसे window functions निकालता है।",
  "Unique": "क्रमबद्ध इनपुट से लगातार आने वाली duplicate पंक्तियाँ हटाता है (DISTINCT)।",
  "Materialize": "अपने इनपुट की पंक्तियाँ मेमोरी में रखता है ताकि उन्हें सस्ते में दोबारा पढ़ा जा सके, जैसे nested loop में।",
  "Memoize": "nested loop के अंदरूनी नतीजों को पैरामीटर के मान से कैश करता है, ताकि दोहराई खोज मुफ़्त हो।",
  "CTE Scan": "एक बार गणना की गई (materialized) WITH क्वेरी की पंक्तियाँ पढ़ता है।",
  "Subquery Scan": "FROM में लिखी subquery का आउटपुट पढ़ता है।",
  "Function Scan": "generate_series() जैसे set-returning function से लौटी पंक्तियाँ पढ़ता है।",
  "Values Scan": "VALUES सूची से पंक्तियाँ पढ़ता है।",
  "Append": "कई इनपुट के आउटपुट को जोड़ता है, जैसे partitioned टेबल के partitions, या UNION ALL।",
  "Result": "टेबल पढ़े बिना कोई मान निकालता है, या एक बार का फ़िल्टर लगाता है।",
  "Gather": "parallel worker processes से पंक्तियाँ इकट्ठा करता है।",
  "SetOp": "INTERSECT या EXCEPT लागू करता है।",
  "ModifyTable": "नीचे से आई पंक्तियों पर INSERT, UPDATE, DELETE या MERGE करता है।",
  "LockRows": "नीचे से आई पंक्तियों को lock करता है (SELECT … FOR UPDATE)।",
};

export const planSamples: Record<string, string> = {
  join: "Join और aggregate",
  seq: "बिना इंडेक्स के फ़िल्टर",
  index: "इंडेक्स के साथ फ़िल्टर",
  topn: "Sort और limit",
  group: "बड़ी टेबल को group करना",
  window: "Window function",
  exists: "EXISTS subquery",
  cte: "Join के साथ CTE",
};
