// Plain-language explanations of PostgreSQL plan nodes.
export const PLAN_NODE_INFO: Record<string, string> = {
  "Seq Scan": "Reads every page of the table in order and checks each row against the filter. Best when a large share of rows match, or there's no useful index.",
  "Index Scan": "Walks the index to find matching keys, then fetches each row from the table. Great for a few rows, and returns them in index order.",
  "Index Only Scan": "Answers from the index alone, without visiting the table, when every needed column is in the index and the pages are marked all-visible.",
  "Bitmap Index Scan": "Scans an index and builds a bitmap of the table pages that hold matches. Feeds a Bitmap Heap Scan.",
  "Bitmap Heap Scan": "Reads the pages marked in the bitmap, in physical order, re-checking the condition. A middle ground between index and sequential scans.",
  "Nested Loop": "For each row from the outer (first) input, looks up matching rows in the inner input. Fast when the outer side is small and the inner side is indexed.",
  "Hash Join": "Builds a hash table from the smaller input, then streams the other input and probes it. Good for large, unsorted equality joins.",
  "Merge Join": "Joins two inputs that are both sorted on the join key, walking them side by side.",
  "Hash": "Builds the in-memory hash table used by the Hash Join above it.",
  "Sort": "Sorts its input, in memory or spilling to disk. Often avoidable with an index that already returns rows in order.",
  "Incremental Sort": "Finishes a sort when the input is already sorted by a prefix of the keys.",
  "Aggregate": "Computes aggregates like count() or sum() over its input.",
  "HashAggregate": "Groups rows with a hash table, then computes each group's aggregates.",
  "GroupAggregate": "Computes aggregates over input already sorted by the group key, one group at a time.",
  "Limit": "Stops after the first N rows, so the nodes below can often stop early too.",
  "WindowAgg": "Computes window functions like rank() or running sums over sorted partitions.",
  "Unique": "Removes adjacent duplicate rows from sorted input (DISTINCT).",
  "Materialize": "Keeps its input's rows in memory so they can be re-read cheaply, e.g. by a nested loop.",
  "Memoize": "Caches inner-side results of a nested loop by parameter value, so repeated lookups are free.",
  "CTE Scan": "Reads the rows of a WITH query that was computed once (materialized).",
  "Subquery Scan": "Reads the output of a subquery in FROM.",
  "Function Scan": "Reads rows returned by a set-returning function such as generate_series().",
  "Values Scan": "Reads rows from a VALUES list.",
  "Append": "Concatenates the outputs of several inputs, e.g. the partitions of a partitioned table, or UNION ALL.",
  "Result": "Computes a value without reading a table, or applies a one-time filter.",
  "Gather": "Collects rows from parallel worker processes.",
  "SetOp": "Implements INTERSECT or EXCEPT.",
  "ModifyTable": "Performs the INSERT, UPDATE, DELETE or MERGE on the rows produced below it.",
  "LockRows": "Locks the rows produced below it (SELECT … FOR UPDATE).",
};

export const planNodeInfo = (type: string) => PLAN_NODE_INFO[type] ?? "A step in the execution plan.";
